[phases.setup]
nixPkgs = [
  "php81.withExtensions (pe: pe.enabled ++ [])",
  "nginx",
  "libmysqlclient",
  "php81Packages.composer",
  "nodejs_18",
  "npm-9_x"
]

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs",
  "npm install"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan key:generate",
  "php artisan migrate --force",
  "php artisan config:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
